/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dasu
 */
public class Change extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Change
     */
    public Change() {
        initComponents();
        conn = DBconnect.connect();
    }
    
    public void changing(){
        int check = JOptionPane.showConfirmDialog(null, "Do you want to change password and username?");
            
        if(check==0){
        String uname = unamebox.getText();
        String pword = pwordbox.getText();
        String vpword = vpwordbox.getText();
        String ans1 = answer1box.getText();
        String ans2 = answer2box.getText();
        
        if(pwordbox.getText().equals(vpwordbox.getText())){
         try {
            
            String sql = "UPDATE fogotpword SET username='"+uname+"', password='"+pword+"',answer1='"+ans1+"', answer2='"+ans2+"'  ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Changed!");
            Login m3 = new Login();
            m3.setVisible(true);
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         
        }
         else {
                 JOptionPane.showMessageDialog(null, "Password do not match");
                 }
        
        
        
    }
    }
    
    
    public void checkpword(){
        
        String curpword = curpwordbox.getText();
        String sql = " select * from fogotpword where password=? ";
        try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, curpwordbox.getText());
                rs = pst.executeQuery();
                
                if(rs.next()){
                     changing();
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Current password is not incorrect");
                }
 
        } catch (Exception e) {
             
             JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        changebtn = new javax.swing.JButton();
        unamebox = new javax.swing.JTextField();
        pwordbox = new javax.swing.JPasswordField();
        vpwordbox = new javax.swing.JPasswordField();
        answer1box = new javax.swing.JTextField();
        answer2box = new javax.swing.JTextField();
        previousebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        curpwordbox = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText(" Change Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 350, 60));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("What is your favourite place?");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("What is your favourite sport?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        changebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        changebtn.setText(" Change");
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });
        jPanel2.add(changebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 100, -1));
        jPanel2.add(unamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, -1));
        jPanel2.add(pwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 180, -1));
        jPanel2.add(vpwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 180, -1));
        jPanel2.add(answer1box, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 180, -1));
        jPanel2.add(answer2box, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 180, -1));

        previousebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousebtn.setText(" Previouse");
        previousebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousebtnActionPerformed(evt);
            }
        });
        jPanel2.add(previousebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Current Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel2.add(curpwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 480, 510));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/1920x1080-Back .jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed
        checkpword();
           
    }//GEN-LAST:event_changebtnActionPerformed

    private void previousebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousebtnActionPerformed
         Login m3 = new Login();
         m3.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_previousebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer1box;
    private javax.swing.JTextField answer2box;
    private javax.swing.JButton changebtn;
    private javax.swing.JPasswordField curpwordbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton previousebtn;
    private javax.swing.JPasswordField pwordbox;
    private javax.swing.JTextField unamebox;
    private javax.swing.JPasswordField vpwordbox;
    // End of variables declaration//GEN-END:variables
}
